name: allocrepes
description: Allo Crêpes

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.14+32


environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  authentication_repository:
    path: packages/authentication_repository

  news_repository:
    path: packages/news_repository

  order_repository:
    path: packages/order_repository

  setting_repository:
    path: packages/setting_repository


  firebase_core: ^2.13.0
  firebase_analytics: ^10.4.1
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.6.1
  cloud_functions: ^4.3.1
  intl: ^0.17.0

  connectivity: ^3.0.6
  package_info_plus: ^4.0.0

  font_awesome_flutter: ^10.4.0

  flutter_html: ^3.0.0-beta.1

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  equatable: ^2.0.5

  url_launcher: ^6.1.11

  loading_overlay: ^0.3.0
  webview_flutter: ^4.2.0

  flexible_scrollbar: ^0.1.3

  cupertino_icons: ^1.0.5

  app_tracking_transparency: ^2.0.4
  flutter_web_auth: ^0.5.0

  flutter_html_iframe: ^3.0.0-beta.1


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/back.png"
  adaptive_icon_foreground: "assets/tete.png"



flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/this_is_xanthos.jpg
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
