name: allocrepes
description: Allo Crêpes

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.14+32


environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  authentication_repository:
    path: packages/authentication_repository

  news_repository:
    path: packages/news_repository

  order_repository:
    path: packages/order_repository


  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.0.12
  firebase_messaging: ^14.2.2
  cloud_functions: ^4.0.8
  intl: ^0.17.0

  connectivity: ^3.0.6
  collection: ^1.17.1
  package_info_plus: ^3.0.3

  font_awesome_flutter: ^10.4.0

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  equatable: ^2.0.5

  url_launcher: ^6.1.9

  loading_overlay: ^0.3.0
  webview_flutter: ^4.0.2

  cupertino_icons: ^1.0.5

  app_tracking_transparency: ^2.0.3
  flutter_web_auth: ^0.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/xanthos.png"
  adaptive_icon_background: "assets/back.png"
  adaptive_icon_foreground: "assets/tete.png"



flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/programRecto.jpg
    - assets/programVerso.jpg
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
