name: allocrepes
description: Allo Crêpes

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.9+27


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  authentication_repository:
    path: packages/authentication_repository

  order_repository:
    path: packages/order_repository

  news_repository:
    path: packages/news_repository


  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  firebase_crashlytics: ^2.0.2
  firebase_messaging: ^9.1.3
  cloud_functions: ^1.0.5
  intl: ^0.17.0

  connectivity: ^3.0.3
  collection: ^1.15.0
  package_info_plus: ^1.0.0

  font_awesome_flutter: ^9.0.0

  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  equatable: ^2.0.0

  url_launcher: ^6.0.2

  loading_overlay: ^0.3.0
  webview_flutter: ^2.0.4

  cupertino_icons: ^1.0.2
  pedantic: ^1.11.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/xanthos.png"
  adaptive_icon_background: "assets/back.png"
  adaptive_icon_foreground: "assets/tete.png"



flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/programRecto.jpg
    - assets/programVerso.jpg
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
