name: news_repository
description: Dart package which manages the news domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  html_unescape: ^2.0.0

  dart_rss: ^2.0.1
  http: ^0.13.5
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter