name: news_repository
description: Dart package which manages the news domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  equatable: ^2.0.5
  html_unescape: ^2.0.0

  http: ^0.13.5
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4