name: order_repository
description: Dart package which manages the editions domain.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.6
  firebase_core: ^0.7.0
  meta: ^1.3.0-nullsafety.3
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0